spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/UsefulArticlesDb
    username: UaUser
    password: uaupass10
    pool:
      name: MAIN-POOL
      initial-size: 1
      max-size: 10
      max-idle-time: 4m
      max-life-time: 9m
#    properties:
#       sslMode: REQUIRE
  cloud:
    config:
      enabled: false
  devtools:
    restart:
      enabled: false

jwt:
  secret: koYiuqmB5IMgbrkdRAyhd6g/ypfAdYr3Ocm4biq+ESUaLPNdmwRnZyZlvQgNh7cewa+hw9/2ZQGE2c/cR+ZYgg==
  session-time: 86400
  
articles:
  attachment:
    storage: file
    base-folder: 'D:\tmp\articles'

debug:
  logging.http-requests: true
  
logging:
  level:
    ROOT: INFO
    com:
      engilyin: DEBUG
    io:
      ROOT: INFO
      spring: DEBUG
      r2dbc:
        postgresql:
          QUERY: DEBUG # for queries
          PARAM: DEBUG # for parameters
    org:
      apache: INFO
      springframework:
        web: 
          ROOT: DEBUG
          server:
            adapter:
              HttpWebHandlerAdapter: TRACE
#          filter:
#            CommonsRequestLoggingFilter: TRACE 
#        http:
#          converter: DEBUG
#    com:
#      fasterxml:
#        jackson: DEBUG
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: FULL